// <auto-generated />
namespace Day30.Practice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedclothes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedclothes));
        
        string IMigrationMetadata.Id
        {
            get { return "202207271659327_addedclothes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
